edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marimo-team/marimo
    - icon: fontawesome/brands/discord
      link: https://marimo.io/discord?ref=docs
    - icon: material/email-newsletter
      link: https://marimo.io/newsletter
    - icon: material/forum
      link: https://marimo.hall.community
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@marimo_io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/marimo_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/marimo-io
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/marimo/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji: null
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          name: mermaid
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - blocks:MarimoBlocksExtension
nav:
  - Getting Started:
      - Home: index.md
      - Overview: getting_started/index.md
      - Installation: getting_started/installation.md
      - Quick Start: getting_started/quickstart.md
      - Key Concepts: getting_started/key_concepts.md
  - User Guide:
      - Overview: guides/index.md
      - Reactivity: guides/reactivity.md
      - Interactivity: guides/interactivity.md
      - State Management: guides/state.md
      - Best Practices: guides/best_practices.md
      - Apps: guides/apps.md
      - Scripts: guides/scripts.md
      - Outputs: guides/outputs.md
      - Expensive Notebooks: guides/expensive_notebooks.md
      - WebAssembly: guides/wasm.md
      - Working with Data:
          - Overview: guides/working_with_data/index.md
          - DataFrames: guides/working_with_data/dataframes.md
          - SQL: guides/working_with_data/sql.md
          - Plotting: guides/working_with_data/plotting.md
      - Coming from:
          - Overview: guides/coming_from/index.md
          - Jupyter: guides/coming_from/jupyter.md
          - Jupytext: guides/coming_from/jupytext.md
          - Papermill: guides/coming_from/papermill.md
          - Streamlit: guides/coming_from/streamlit.md
      - Configuration:
          - Overview: guides/configuration/index.md
          - HTML Head: guides/configuration/html_head.md
          - Runtime Configuration: guides/configuration/runtime_configuration.md
          - Theming: guides/configuration/theming.md
      - Deployment:
          - Overview: guides/deploying/index.md
          - Authentication: guides/deploying/authentication.md
          - Docker: guides/deploying/deploying_docker.md
          - Hugging Face: guides/deploying/deploying_hugging_face.md
          - Ploomber: guides/deploying/deploying_ploomber.md
          - Public Gallery: guides/deploying/deploying_public_gallery.md
          - Railway: guides/deploying/deploying_railway.md
          - Prebuilt Containers: guides/deploying/prebuilt_containers.md
          - Programmatic: guides/deploying/programmatically.md
      - Editor Features:
          - Overview: guides/editor_features/index.md
          - AI Completion: guides/editor_features/ai_completion.md
          - Hotkeys: guides/editor_features/hotkeys.md
          - Package Management: guides/editor_features/package_management.md
      - Integrating with Marimo:
          - Overview: guides/integrating_with_marimo/index.md
          - Custom UI Plugins: guides/integrating_with_marimo/custom_ui_plugins.md
          - Displaying Objects: guides/integrating_with_marimo/displaying_objects.md
  - API Reference:
      - Overview: api/index.md
      - App: api/app.md
      - Caching: api/caching.md
      - Cell: api/cell.md
      - CLI Arguments: api/cli_args.md
      - Control Flow: api/control_flow.md
      - Diagrams: api/diagrams.md
      - HTML: api/html.md
      - Markdown: api/markdown.md
      - Outputs: api/outputs.md
      - Plotting: api/plotting.md
      - Query Parameters: api/query_params.md
      - State: api/state.md
      - Status: api/status.md
      - Inputs:
          - Overview: api/inputs/index.md
          - AnyWidget: api/inputs/anywidget.md
          - Array: api/inputs/array.md
          - Batch: api/inputs/batch.md
          - Button: api/inputs/button.md
          - Chat: api/inputs/chat.md
          - Checkbox: api/inputs/checkbox.md
          - Code Editor: api/inputs/code_editor.md
          - Data Explorer: api/inputs/data_explorer.md
          - DataFrame: api/inputs/dataframe.md
          - Dates: api/inputs/dates.md
          - Dictionary: api/inputs/dictionary.md
          - Dropdown: api/inputs/dropdown.md
          - File: api/inputs/file.md
          - File Browser: api/inputs/file_browser.md
          - Form: api/inputs/form.md
          - Microphone: api/inputs/microphone.md
          - Multiselect: api/inputs/multiselect.md
          - Navigation Menu: api/inputs/nav_menu.md
          - Number: api/inputs/number.md
          - Radio: api/inputs/radio.md
          - Range Slider: api/inputs/range_slider.md
          - Refresh: api/inputs/refresh.md
          - Run Button: api/inputs/run_button.md
          - Slider: api/inputs/slider.md
          - Switch: api/inputs/switch.md
          - Table: api/inputs/table.md
          - Tabs: api/inputs/tabs.md
          - Text: api/inputs/text.md
          - Text Area: api/inputs/text_area.md
      - Layouts:
          - Overview: api/layouts/index.md
          - Accordion: api/layouts/accordion.md
          - Callout: api/layouts/callout.md
          - Carousel: api/layouts/carousel.md
          - Justify: api/layouts/justify.md
          - Lazy: api/layouts/lazy.md
          - Plain: api/layouts/plain.md
          - Routes: api/layouts/routes.md
          - Sidebar: api/layouts/sidebar.md
          - Stacks: api/layouts/stacks.md
          - Tree: api/layouts/tree.md
      - Media:
          - Overview: api/media/index.md
          - Audio: api/media/audio.md
          - Download: api/media/download.md
          - Image: api/media/image.md
          - PDF: api/media/pdf.md
          - Plain Text: api/media/plain_text.md
          - Video: api/media/video.md
  - Integrations:
      - Overview: integrations/index.md
      - BigQuery: integrations/google_cloud_bigquery.md
      - Google Cloud Storage: integrations/google_cloud_storage.md
      - Google Sheets: integrations/google_sheets.md
      - MotherDuck: integrations/motherduck.md
  - Community:
      - Overview: community.md
      - FAQ: faq.md
      - Examples: examples.md
      - Recipes: recipes.md
      - Contributing: https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md
      - Code of Conduct: https://github.com/marimo-team/marimo/blob/main/CODE_OF_CONDUCT.md
  - Development:
      - Migration Plan: plan.md
      - Miscellaneous: api/miscellaneous.md
      - Editor Features:
          - Overview: guides/editor_features/overview.md
      - Apps:
          - Overview: apps/README.md
      - Troubleshooting: guides/troubleshooting.md
      - Exporting: guides/exporting.md
      - Island Example: guides/island_example.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          load_external_modules: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
          options:
            allow_inspection: true
            docstring_section_style: spacy
            docstring_style: google
            heading_level: 2
            inherited_members: true
            members: true
            merge_init_into_class: true
            show_bases: true
            show_if_no_docstring: true
            show_root_heading: true
            show_root_members: true
            show_source: false
            show_submodules: true
            find_stubs_package: true
            filters:
              - '!^_'
  - autorefs
repo_name: marimo-team/marimo
repo_url: https://github.com/marimo-team/marimo
site_description: A library for making reactive notebooks and apps
site_name: marimo
site_url: https://docs.marimo.io
theme:
  favicon: _static/favicon-32x32.png
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - search.highlight
  font:
    code:
      - Roboto Mono
    text:
      - Inter
      - Roboto
  logo: _static/marimo-logotype-thick.svg
  name: material
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/link
        name: Switch to light mode
    - accent: indigo
      media: '(prefers-color-scheme: light)'
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - accent: indigo
      media: '(prefers-color-scheme: dark)'
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
