edit_uri: edit/main/docs/
copyright: 'Â© marimo 2024'
watch:
  - docs/
  - marimo/
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marimo-team/marimo
    - icon: fontawesome/brands/discord
      link: https://marimo.io/discord?ref=docs
    - icon: material/email-newsletter
      link: https://marimo.io/newsletter
    - icon: material/forum
      link: https://community.marimo.io
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@marimo_io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/marimo_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/marimo-io
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/marimo/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@marimo-team
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - _static/js/analytics.js
  - _static/js/math.js
  - _static/js/init_kapa_widget.js
markdown_extensions:
  - blocks:MarimoBlocksExtension
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists # lists separated by paragraphs
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji: null
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mkdocs-click
nav:
  - Marimo: index.md
  - Getting Started:
      - Getting Started: getting_started/index.md
      - Installation: getting_started/installation.md
      - Quickstart: getting_started/quickstart.md
      - Key Concepts: getting_started/key_concepts.md

  - User Guide:
      - User Guide: guides/index.md
      - Running cells: guides/reactivity.md
      - Interactive elements: guides/interactivity.md
      - Visualize outputs: guides/outputs.md
      - Migrate from Jupyter: guides/coming_from/jupyter.md
      - Expensive notebooks: guides/expensive_notebooks.md
      - Understanding errors:
          - Understanding errors: guides/understanding_errors/index.md
          - Multiple definitions: guides/understanding_errors/multiple_definitions.md
          - Import star: guides/understanding_errors/import_star.md
          - Cycles: guides/understanding_errors/cycles.md
          - Setup References: guides/understanding_errors/setup.md
      - SQL, dataframes, and plots:
          - SQL, dataframes, and plots: guides/working_with_data/index.md
          - DataFrames: guides/working_with_data/dataframes.md
          - SQL: guides/working_with_data/sql.md
          - Plotting: guides/working_with_data/plotting.md
      - Package reproducibility: guides/package_reproducibility.md
      - Generate with AI:
          - Generate with AI: guides/generate_with_ai/index.md
          - Generate entire notebooks: guides/generate_with_ai/text_to_notebook.md
          - AI-assisted coding: guides/editor_features/ai_completion.md
      - Editor features:
          - Editor features: guides/editor_features/index.md
          - Editor overview: guides/editor_features/overview.md
          - AI completion: guides/editor_features/ai_completion.md
          - Language Server: guides/editor_features/language_server.md
          - Package management: guides/editor_features/package_management.md
          - Module autoreloading: guides/editor_features/module_autoreloading.md
          - Hotkeys: guides/editor_features/hotkeys.md
      - Using your own editor: guides/editor_features/watching.md
      - Run notebooks as apps: guides/apps.md
      - Run notebooks as scripts: guides/scripts.md
      - Test notebooks:
          - Testing notebooks: guides/testing/index.md
          - pytest: guides/testing/pytest.md
          - doctest: guides/testing/doctest.md
      - Reusing functions and classes: guides/reusing_functions.md
      - Export to other formats: guides/exporting.md
      - Publish to the web:
          - Publish to the web: guides/publishing/index.md
          - Embedding: guides/publishing/embedding.md
          - From code snippets: guides/publishing/from_code_snippets.md
          - From GitHub: guides/publishing/from_github.md
          - GitHub Pages: guides/publishing/github_pages.md
          - Cloudflare Pages: guides/publishing/cloudflare_pages.md
          - Online playground: guides/publishing/playground.md
          - Community Cloud: guides/publishing/community_cloud/index.md
          - Self-host WASM: guides/publishing/self_host_wasm.md
          - View outputs on GitHub: guides/publishing/view_outputs_on_github.md
          - Deploy a backend: guides/publishing/deploy.md
      - Deployment:
          - Deploy notebooks: guides/deploying/index.md
          - Authentication: guides/deploying/authentication.md
          - Docker: guides/deploying/deploying_docker.md
          - HuggingFace: guides/deploying/deploying_hugging_face.md
          - Ploomber: guides/deploying/deploying_ploomber.md
          - Public gallery: guides/deploying/deploying_public_gallery.md
          - Railway: guides/deploying/deploying_railway.md
          - nginx: guides/deploying/deploying_nginx.md
          - Prebuilt containers: guides/deploying/prebuilt_containers.md
          - Programmatic: guides/deploying/programmatically.md
      - WebAssembly notebooks: guides/wasm.md
      - Configuration:
          - Configuration: guides/configuration/index.md
          - Runtime configuration: guides/configuration/runtime_configuration.md
          - HTML head: guides/configuration/html_head.md
          - Theming: guides/configuration/theming.md
          - Snippets: guides/configuration/snippets.md
      - Coming from other tools:
          - Coming from other tools: guides/coming_from/index.md
          - Jupytext: guides/coming_from/jupytext.md
          - Papermill: guides/coming_from/papermill.md
          - Streamlit: guides/coming_from/streamlit.md
      - Extending marimo:
          - Extending marimo: guides/integrating_with_marimo/index.md
          - Custom UI plugins: guides/integrating_with_marimo/custom_ui_plugins.md
          - Displaying objects: guides/integrating_with_marimo/displaying_objects.md
      - Best practices: guides/best_practices.md
      - Troubleshooting: guides/troubleshooting.md
      - Dangerously set state: guides/state.md
  - API Reference:
      - API Reference: api/index.md
      - Markdown: api/markdown.md
      - Inputs:
          - Inputs: api/inputs/index.md
          - AnyWidget: api/inputs/anywidget.md
          - Array: api/inputs/array.md
          - Batch: api/inputs/batch.md
          - Button: api/inputs/button.md
          - Chat: api/inputs/chat.md
          - Checkbox: api/inputs/checkbox.md
          - Code Editor: api/inputs/code_editor.md
          - Data Explorer: api/inputs/data_explorer.md
          - DataFrame: api/inputs/dataframe.md
          - Dates: api/inputs/dates.md
          - Dictionary: api/inputs/dictionary.md
          - Dropdown: api/inputs/dropdown.md
          - File: api/inputs/file.md
          - File Browser: api/inputs/file_browser.md
          - Form: api/inputs/form.md
          - Microphone: api/inputs/microphone.md
          - Multiselect: api/inputs/multiselect.md
          - Navigation Menu: api/inputs/nav_menu.md
          - Number: api/inputs/number.md
          - Radio: api/inputs/radio.md
          - Range Slider: api/inputs/range_slider.md
          - Refresh: api/inputs/refresh.md
          - Run Button: api/inputs/run_button.md
          - Slider: api/inputs/slider.md
          - Switch: api/inputs/switch.md
          - Table: api/inputs/table.md
          - Tabs: api/inputs/tabs.md
          - Text: api/inputs/text.md
          - Text Area: api/inputs/text_area.md
      - Control Flow: api/control_flow.md
      - Layouts:
          - Layouts: api/layouts/index.md
          - Accordion: api/layouts/accordion.md
          - Callout: api/layouts/callout.md
          - Carousel: api/layouts/carousel.md
          - Json: api/layouts/json.md
          - Justify: api/layouts/justify.md
          - Lazy: api/layouts/lazy.md
          - Plain: api/layouts/plain.md
          - Routes: api/layouts/routes.md
          - Sidebar: api/layouts/sidebar.md
          - Stat: api/layouts/stat.md
          - Stacks: api/layouts/stacks.md
          - Tree: api/layouts/tree.md
      - Plotting: api/plotting.md
      - Media:
          - Media: api/media/index.md
          - Audio: api/media/audio.md
          - Download: api/media/download.md
          - Image: api/media/image.md
          - PDF: api/media/pdf.md
          - Plain Text: api/media/plain_text.md
          - Video: api/media/video.md
      - Progress Bars and Status: api/status.md
      - Outputs: api/outputs.md
      - Diagrams: api/diagrams.md
      - HTML: api/html.md
      - Query Parameters: api/query_params.md
      - Command Line Arguments: api/cli_args.md
      - Caching: api/caching.md
      - State: api/state.md
      - App: api/app.md
      - Cell: api/cell.md
      - Miscellaneous: api/miscellaneous.md
  - Commands: cli.md
  - Examples:
      - Notebooks: examples.md
      - Recipes: recipes.md
      - Islands: guides/island_example.md
  - FAQ: faq.md
  - Community:
      - Community: community.md
      - Contributing: https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md
      - Code of Conduct: https://github.com/marimo-team/marimo/blob/main/CODE_OF_CONDUCT.md
  - Integrations:
      - Integrations: integrations/index.md
      - BigQuery: integrations/google_cloud_bigquery.md
      - Google Cloud Storage: integrations/google_cloud_storage.md
      - Google Sheets: integrations/google_sheets.md
      - MotherDuck: integrations/motherduck.md
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: '#FFFFFF'
        color: '#000000'
        font_family: Roboto
  - tags
  - redirects:
      redirect_maps: {}
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          load_external_modules: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
          options:
            preload_modules:
              - starlette
            filters:
              - '!^_'
            # General
            allow_inspection: false
            show_bases: true
            show_source: false
            find_stubs_package: true
            # Headings
            heading_level: 2
            show_root_heading: true
            # Members
            inherited_members: true
            # Docstrings
            merge_init_into_class: true
            show_if_no_docstring: true
            docstring_section_style: spacy
            docstring_style: google
            # Signatures
            separate_signature: true
            unwrap_annotated: true
            annotations_path: brief
            line_length: 60
            modernize_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
  - autorefs
hooks:
  - docs/hooks.py
repo_name: marimo-team/marimo
repo_url: https://github.com/marimo-team/marimo
site_description: The next generation of Python notebooks
site_name: marimo
site_url: https://docs.marimo.io
theme:
  favicon: _static/favicon-32x32.png
  features:
    - announce.dismiss # dismissible announcements
    - content.code.copy # add copy button to code blocks
    - header.autohide # auto-hide header on scroll
    - navigation.indexes # section index pages
    - navigation.instant # faster page loads
    - navigation.path # show navigation breadcrumb path
    - navigation.tabs # show navigation as tabs
    - navigation.tabs.sticky # keep navigation tabs visible when scrolling
    - navigation.top # back to top button
    - navigation.tracking # updates URL as you scroll
    - navigation.footer # links to previous/next page, helpful for small screens
    - search.highlight # highlight search results
    - search.share # shareable search links
    - search.suggest # search suggestions
    - toc.follow # auto-scroll TOC
  font:
    code: Fira Mono
    text: PT Sans
  logo: _static/marimo-logotype-horizontal.png
  name: material
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      primary: white
      accent: teal
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: black
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
