name: Build and Deploy Docs

on:
  # Deploy on push to main
  push:
    branches: [main]
  # Deploy on workflow dispatch
  workflow_dispatch: {}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v4

      - name: üêç Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: 3.12

      - name: ‚ö° Install Vercel CLI
        run: npm install --global vercel@latest

      - name: ‚¨áÔ∏è Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: üìö Build docs
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: üìö llms.txt
        # This is technically off by 1 commit, but generating the llms.txt file is easiest from a
        # deployed site.
        # We also ignore txt and xml files
        run: npx sitefetch https://docs.marimo.io -o ${{ env.OUTPUT_FILE }} --match '!**/*.{txt,xml}'
        env:
          OUTPUT_FILE: .vercel/output/static/llms.txt

      - name: üìö CLAUDE.md
        run: cp docs/_static/CLAUDE.md .vercel/output/static/CLAUDE.md

      - name: üöÄ Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
