name: üè∑Ô∏è Pull Request Labeler

# Label pull requests based on config in .github/labeler.yml
# Then enforce that at least one label is selected

on:
  pull_request_target:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  enforce-label:
    needs: [label]
    if: always() && (needs.label.result == 'success' || needs.label.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "enhancement,bug,documentation,internal,preview,other"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['enhancement','bug','documentation','internal','preview','other']"
