name: Test FE

# Run on push to main and pull requests
# only for changes in the frontend directory
on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'lsp/**'
      - 'openapi/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'lsp/**'
      - 'openapi/**'

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: marimo
  MARIMO_SKIP_UPDATE_CHECK: 1

jobs:
  test_frontend:
    name: ğŸ–¥ï¸ Lint, test, build frontend
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./frontend
        shell: bash

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so we can run --since on the main branch and turbo can do faster cache hashing

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: â” Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - uses: turbocache-build/turbocache-action@v1

      - name: ğŸ“¥ Install dependencies
        run: pnpm install

      - name: ğŸ“¦ pnpm dedupe
        if: github.event_name == 'pull_request'
        run: pnpm dedupe --check

      - name: ğŸ§¹ Lint
        run: pnpm turbo lint

      - name: ğŸ” Type check
        run: pnpm turbo typecheck

      - name: ğŸ§ª Test
        run: pnpm test

      - name: ğŸ“¦ Build
        run: pnpm turbo build
        env:
          NODE_ENV: production

      - name: ğŸ“¦ Build islands frontend
        env:
          NODE_ENV: production
          VITE_MARIMO_ISLANDS: 'true'
          VITE_MARIMO_VERSION: '0.0.0'
        run: |
          npm version 0.0.0 --no-git-tag-version
          pnpm turbo build:islands
          ./islands/validate.sh
